export const REGISTRATION_SERVICE = 'REGISTRATION_SERVICE';
export const VERIFICATION_SERVICE = 'VERIFICATION_SERVICE';
export const DOCUMENT_SERVICE = 'DOCUMENT_SERVICE';
export const CEP_SERVICE = 'CEP_SERVICE';
