export const ENV_VARS = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  PROJECT_NAME: 'PROJECT_NAME',
  MONGO_URI: 'MONGO_URI',
  CACHE_REDIS_HOST: 'CACHE_REDIS_HOST',
  CACHE_REDIS_PORT: 'CACHE_REDIS_PORT',
  CACHE_REDIS_PASSWORD: 'CACHE_REDIS_PASSWORD',
  API_BASE_URL: 'API_BASE_URL',
  API_TIMEOUT_MS: 'API_TIMEOUT_MS',
  WS_CORS_ORIGINS: 'WS_CORS_ORIGINS',
  CACHE_TTL_HOME: 'CACHE_TTL_HOME',
  CACHE_TTL_SEARCH: 'CACHE_TTL_SEARCH',
  CACHE_TTL_PROVIDER_PROFILE: 'CACHE_TTL_PROVIDER_PROFILE',
  CACHE_TTL_DASHBOARD: 'CACHE_TTL_DASHBOARD',
  KEYCLOAK_BASE_URL: 'KEYCLOAK_BASE_URL',
  KEYCLOAK_REALM: 'KEYCLOAK_REALM',
  KEYCLOAK_ADMIN_USER: 'KEYCLOAK_ADMIN_USER',
  KEYCLOAK_ADMIN_PASSWORD: 'KEYCLOAK_ADMIN_PASSWORD',
} as const;

export const SWAGGER_CUSTOM_CSS = '';

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;
